require:
  - rubocop-rails

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'bin/*'

Metrics/LineLength:
  Max: 128

Metrics/MethodLength:
  Max: 20

Naming/UncommunicativeMethodParamName:
  AllowedNames:
    - e

Style/Documentation:
  Enabled: false
