default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: 127.0.0.1
  port: 5432

development:
  <<: *default
  database: magicami_closet_development

test:
  <<: *default
  database: magicami_closet_test

production:
  <<: *default
  database: magicami_closet_production
